### ISSUE TITLE
Trying to pass the client id to authenticate the app doesn't seem possible

### ISSUE THREAD

**Issue by sanders2096** [okta/samples-java-servlet#21]
We don't want to authenticate against just the org - passing the client id via the audience parameter - even though it says deprecated doesn't seem to work. Just get an error that audience is not supported.

**Comment by arvindkrishnakumar-okta** [comment]
@sanders2096 Thanks for posting.

We don't actively maintain this repo. I recommend you checkout the repo https://github.com/okta/samples-java-spring instead.
